### ISSUE TITLE
关于训练的数据来源

### ISSUE THREAD

**Issue by 18894269590** [hq-deng/AnoVL#2]
作者，您好，文章是做的零样本，也提到只使用了 MVTecAD和 Visa两个数据集，可是，也做了训练，请问是怎么训练的，用的什么数据做的训练？

**Comment by hq-deng** [comment]
Hello,
We use **test-time adaptation**, which can finetune the model with the test data. In inference, for a test sample _x_, we can augment the sample _x_ and we obtain more samples so that we can finetune the model. Note in this study, we only augment the features not the samples, which make our work different from other test-time augmentation studies.

**Comment by hq-deng** [comment]
Please refer to Test-time prompt tuning for zero-shot generalization in vision-language models.

**Comment by 18894269590** [comment]
Oh, thank you, I understand.
